In [1]:
import pandas as pd 
import numpy as np

# SOLAR RADIATION PREDICTION ML MODEL

In [2]:
df = pd.read_csv('test_df_1.csv')
df

,ID,UNIXTime,Data,Time,Temperature,Pressure,Humidity,WindDirection(Degrees),Speed,TimeSunRise,TimeSunSet
0,1,1479500121,18-11-2016,10:15:21,53.000000,30.44,NaN,75.85,6.750000,06:33:00,17:43:00
1,2,1482676595,25-12-2016,04:36:35,46.000000,NaN,31.0,173.63,NaN,06:55:00,17:51:00
2,3,1478672401,08-11-2016,20:20:01,48.000000,30.46,99.0,220.98,1.120000,06:27:00,17:45:00
3,4,1483252803,31-12-2016,20:40:03,43.000000,NaN,88.0,208.21,16.364613,06:57:00,17:54:00
4,5,1472903703,03-09-2016,01:55:03,52.000000,30.42,96.0,163.78,4.500000,06:08:00,18:36:00
...,...,...,...,...,...,...,...,...,...,...,...
3329,3330,1477438818,25-10-2016,13:40:18,65.000000,30.44,65.0,85.00,7.870000,06:21:00,17:52:00
3330,3331,1479917102,23-11-2016,06:05:02,40.000000,30.41,90.0,77.26,11.250000,06:36:00,17:42:00
3331,3332,1479524118,18-11-2016,16:55:18,123.454239,30.39,64.0,127.90,12.370000,06:33:00,17:43:00
3332,3333,1474546822,22-09-2016,02:20:22,49.000000,30.39,101.0,114.67,4.500000,06:11:00,18:19:00
3333,3334,1475012428,27-09-2016,11:40:28,63.000000,30.40,69.0,65.38,1.120000,06:13:00,18:15:00

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3334 entries, 0 to 3333
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      3334 non-null   int64
 1   UNIXTime                3334 non-null   int64
 2   Data                    3334 non-null   str
 3   Time                    3334 non-null   str
 4   Temperature             3179 non-null   float64
 5   Pressure                3180 non-null   float64
 6   Humidity                3156 non-null   float64
 7   WindDirection(Degrees)  3334 non-null   float64
 8   Speed                   3178 non-null   float64
 9   TimeSunRise             3334 non-null   str
 10  TimeSunSet              3334 non-null   str
dtypes: float64(5), int64(2), str(4)
memory usage: 397.3 KB

In [4]:
import matplotlib.pyplot as plt
plt.figure()

In [5]:
df['Temperature'].isnull().sum()

np.int64(155)

In [6]:
df['Pressure'].isnull().sum()

np.int64(154)

In [7]:
df['Humidity'].isnull().sum()

np.int64(178)

In [8]:
df['Speed'].isnull().sum()

np.int64(156)

In [9]:
df['Speed']

0        6.750000
1             NaN
2        1.120000
3       16.364613
4        4.500000
          ...
3329     7.870000
3330    11.250000
3331    12.370000
3332     4.500000
3333     1.120000
Name: Speed, Length: 3334, dtype: float64

In [10]:
mean_speed = df['Speed'].dropna().mean()

In [11]:
df['Speed']=df['Speed'].fillna(mean_speed)

In [12]:
df['Speed'].isnull().sum()

np.int64(0)

In [13]:
df['Pressure']

0       30.44
1         NaN
2       30.46
3         NaN
4       30.42
        ...
3329    30.44
3330    30.41
3331    30.39
3332    30.39
3333    30.40
Name: Pressure, Length: 3334, dtype: float64

In [14]:
mean_pressure = df['Pressure'].dropna().mean()

In [15]:
df['Pressure'] = df['Pressure'].fillna(mean_pressure)

In [16]:
df['Pressure']

0       30.440000
1       30.422855
2       30.460000
3       30.422855
4       30.420000
          ...
3329    30.440000
3330    30.410000
3331    30.390000
3332    30.390000
3333    30.400000
Name: Pressure, Length: 3334, dtype: float64

In [17]:
df['Humidity']

0         NaN
1        31.0
2        99.0
3        88.0
4        96.0
        ...
3329     65.0
3330     90.0
3331     64.0
3332    101.0
3333     69.0
Name: Humidity, Length: 3334, dtype: float64

In [18]:
mean_humidity = df['Humidity'].dropna().mean()

In [19]:
df['Humidity'] = df['Humidity'].fillna(mean_humidity)

In [20]:
df['Humidity']

0        75.960462
1        31.000000
2        99.000000
3        88.000000
4        96.000000
           ...
3329     65.000000
3330     90.000000
3331     64.000000
3332    101.000000
3333     69.000000
Name: Humidity, Length: 3334, dtype: float64

In [21]:
df['Humidity']

0        75.960462
1        31.000000
2        99.000000
3        88.000000
4        96.000000
           ...
3329     65.000000
3330     90.000000
3331     64.000000
3332    101.000000
3333     69.000000
Name: Humidity, Length: 3334, dtype: float64

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3334 entries, 0 to 3333
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      3334 non-null   int64
 1   UNIXTime                3334 non-null   int64
 2   Data                    3334 non-null   str
 3   Time                    3334 non-null   str
 4   Temperature             3179 non-null   float64
 5   Pressure                3334 non-null   float64
 6   Humidity                3334 non-null   float64
 7   WindDirection(Degrees)  3334 non-null   float64
 8   Speed                   3334 non-null   float64
 9   TimeSunRise             3334 non-null   str
 10  TimeSunSet              3334 non-null   str
dtypes: float64(5), int64(2), str(4)
memory usage: 397.3 KB

In [23]:
mean_temp = df['Temperature'].dropna().mean()

In [24]:
df['Temperature']=df['Temperature'].fillna(mean_temp)

In [25]:
df['Date'] = df['Data']

In [26]:
df = df.drop('Data',axis=1)

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3334 entries, 0 to 3333
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      3334 non-null   int64
 1   UNIXTime                3334 non-null   int64
 2   Time                    3334 non-null   str
 3   Temperature             3334 non-null   float64
 4   Pressure                3334 non-null   float64
 5   Humidity                3334 non-null   float64
 6   WindDirection(Degrees)  3334 non-null   float64
 7   Speed                   3334 non-null   float64
 8   TimeSunRise             3334 non-null   str
 9   TimeSunSet              3334 non-null   str
 10  Date                    3334 non-null   str
dtypes: float64(5), int64(2), str(4)
memory usage: 397.3 KB

In [28]:
df['Date'] = pd.to_datetime(df['Date'])

C:\Users\WELCOME\AppData\Local\Temp\ipykernel_6276\2394721818.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Date'] = pd.to_datetime(df['Date'])

In [29]:
df['Date']

0      2016-11-18
1      2016-12-25
2      2016-11-08
3      2016-12-31
4      2016-09-03
          ...
3329   2016-10-25
3330   2016-11-23
3331   2016-11-18
3332   2016-09-22
3333   2016-09-27
Name: Date, Length: 3334, dtype: datetime64[us]

In [30]:
df['Date_num'] = df['Date'].astype('int64')

In [31]:
df['Date_num']

0       1479427200000000
1       1482624000000000
2       1478563200000000
3       1483142400000000
4       1472860800000000
              ...
3329    1477353600000000
3330    1479859200000000
3331    1479427200000000
3332    1474502400000000
3333    1474934400000000
Name: Date_num, Length: 3334, dtype: int64

In [32]:
from sklearn.preprocessing import StandardScaler
std_date = StandardScaler()
df['Date_num'] = std_date.fit_transform(df[['Date_num']])

In [33]:
df['Date_num']

0       0.505514
1       1.568414
2       0.218244
3       1.740776
4      -1.677739
          ...
3329   -0.183934
3330    0.649150
3331    0.505514
3332   -1.131925
3333   -0.988290
Name: Date_num, Length: 3334, dtype: float64

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3334 entries, 0 to 3333
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      3334 non-null   int64
 1   UNIXTime                3334 non-null   int64
 2   Time                    3334 non-null   str
 3   Temperature             3334 non-null   float64
 4   Pressure                3334 non-null   float64
 5   Humidity                3334 non-null   float64
 6   WindDirection(Degrees)  3334 non-null   float64
 7   Speed                   3334 non-null   float64
 8   TimeSunRise             3334 non-null   str
 9   TimeSunSet              3334 non-null   str
 10  Date                    3334 non-null   datetime64[us]
 11  Date_num                3334 non-null   float64
dtypes: datetime64[us](1), float64(6), int64(2), str(3)
memory usage: 390.8 KB

In [35]:
df['UNIXTime']

0       1479500121
1       1482676595
2       1478672401
3       1483252803
4       1472903703
           ...
3329    1477438818
3330    1479917102
3331    1479524118
3332    1474546822
3333    1475012428
Name: UNIXTime, Length: 3334, dtype: int64

In [36]:
std_unix = StandardScaler()
df['UNIXTime'] = std_unix.fit_transform(df[['UNIXTime']])

In [37]:
df['UNIXTime']

0       0.503098
1       1.559344
2       0.227863
3       1.750946
4      -1.690353
          ...
3329   -0.182330
3330    0.641753
3331    0.511078
3332   -1.143981
3333   -0.989157
Name: UNIXTime, Length: 3334, dtype: float64

In [38]:
df_test_set = df[['Pressure','Humidity','Temperature','Speed','WindDirection(Degrees)','UNIXTime','Date_num']]

In [39]:
df_train = pd.read_csv('train_df_1.csv')

In [40]:
df_train

,ID,UNIXTime,Data,Time,Radiation,Temperature,Pressure,Humidity,WindDirection(Degrees),Speed,TimeSunRise,TimeSunSet
0,1,1477545019,26-10-2016,19:10:19,4.294954,48.0,30.41,93.0,124.57,11.25,06:21:00,17:52:00
1,2,1477379721,24-10-2016,21:15:21,4.439169,47.0,30.47,81.0,148.63,5.62,06:21:00,17:53:00
2,3,1477689619,28-10-2016,11:20:19,483.267515,51.0,30.42,100.0,19.15,3.37,06:22:00,17:51:00
3,4,1476002422,08-10-2016,22:40:22,5.950979,50.0,30.43,90.0,189.05,5.62,06:15:00,18:05:00
4,5,1477146317,22-10-2016,04:25:17,-8.324804,49.0,NaN,102.0,117.63,4.50,06:20:00,17:54:00
...,...,...,...,...,...,...,...,...,...,...,...,...
19999,20000,1473681318,12-09-2016,01:55:18,10.210194,47.0,30.48,92.0,177.64,6.75,06:09:00,18:28:00
20000,20001,1475878823,07-10-2016,12:20:23,323.399022,60.0,NaN,82.0,353.49,4.50,06:15:00,18:06:00
20001,20002,1474394104,20-09-2016,07:55:04,419.397035,57.0,30.41,54.0,80.83,3.37,06:11:00,18:21:00
20002,20003,1473762608,13-09-2016,00:30:08,4.582930,50.0,30.48,92.0,196.60,6.75,06:10:00,18:27:00
20003,20004,1473825602,13-09-2016,18:00:02,15.813488,56.0,30.40,97.0,354.47,2.25,06:10:00,18:27:00

In [41]:
df_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 20004 entries, 0 to 20003
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      20004 non-null  int64
 1   UNIXTime                20004 non-null  int64
 2   Data                    20004 non-null  str
 3   Time                    20004 non-null  str
 4   Radiation               20004 non-null  float64
 5   Temperature             18978 non-null  float64
 6   Pressure                18982 non-null  float64
 7   Humidity                18995 non-null  float64
 8   WindDirection(Degrees)  20004 non-null  float64
 9   Speed                   19055 non-null  float64
 10  TimeSunRise             20004 non-null  str
 11  TimeSunSet              20004 non-null  str
dtypes: float64(6), int64(2), str(4)
memory usage: 2.5 MB

In [42]:
df_train['Temperature'].isnull().sum()

np.int64(1026)

In [43]:
mean_temp_train = df_train['Temperature'].dropna().mean()

In [44]:
df_train['Temperature']=df_train['Temperature'].fillna(mean_temp_train)

In [45]:
df_train['Pressure'].isnull().sum()

np.int64(1022)

In [46]:
mean_pressure_train = df_train['Pressure'].dropna().mean()

In [47]:
df_train['Pressure']=df_train['Pressure'].fillna(mean_pressure_train)

In [48]:
df_train['Speed'].isnull().sum()

np.int64(949)

In [49]:
mean_speed_train = df_train['Speed'].dropna().mean()

In [50]:
df_train['Speed']=df_train['Speed'].fillna(mean_speed_train)

In [51]:
df_train['Humidity'].isnull().sum()

np.int64(1009)

In [52]:
mean_humidity_train = df_train['Humidity'].dropna().mean()

In [53]:
df_train['Humidity']=df_train['Humidity'].fillna(mean_humidity_train)

In [54]:
df_train['Date'] = df_train['Data']

In [55]:
df_train=df_train.drop('Data',axis=1)

In [56]:
df_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 20004 entries, 0 to 20003
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      20004 non-null  int64
 1   UNIXTime                20004 non-null  int64
 2   Time                    20004 non-null  str
 3   Radiation               20004 non-null  float64
 4   Temperature             20004 non-null  float64
 5   Pressure                20004 non-null  float64
 6   Humidity                20004 non-null  float64
 7   WindDirection(Degrees)  20004 non-null  float64
 8   Speed                   20004 non-null  float64
 9   TimeSunRise             20004 non-null  str
 10  TimeSunSet              20004 non-null  str
 11  Date                    20004 non-null  str
dtypes: float64(6), int64(2), str(4)
memory usage: 2.5 MB

In [57]:
df_test_set.info()

<class 'pandas.DataFrame'>
RangeIndex: 3334 entries, 0 to 3333
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Pressure                3334 non-null   float64
 1   Humidity                3334 non-null   float64
 2   Temperature             3334 non-null   float64
 3   Speed                   3334 non-null   float64
 4   WindDirection(Degrees)  3334 non-null   float64
 5   UNIXTime                3334 non-null   float64
 6   Date_num                3334 non-null   float64
dtypes: float64(7)
memory usage: 182.5 KB

In [58]:
df_train['Date_num']=pd.to_datetime(df_train['Date']).astype('int64')

C:\Users\WELCOME\AppData\Local\Temp\ipykernel_6276\2173259646.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_train['Date_num']=pd.to_datetime(df_train['Date']).astype('int64')

In [59]:
df_train['Date_num']

0        1477440000000000
1        1477267200000000
2        1477612800000000
3        1475884800000000
4        1477094400000000
               ...
19999    1473638400000000
20000    1475798400000000
20001    1474329600000000
20002    1473724800000000
20003    1473724800000000
Name: Date_num, Length: 20004, dtype: int64

In [60]:
df_train['Date_num'] = std_date.fit_transform(df_train[['Date_num']])

In [61]:
df_train['UNIXTime'] = std_unix.fit_transform(df_train[['UNIXTime']])

In [62]:
df_train.info()

<class 'pandas.DataFrame'>
RangeIndex: 20004 entries, 0 to 20003
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      20004 non-null  int64
 1   UNIXTime                20004 non-null  float64
 2   Time                    20004 non-null  str
 3   Radiation               20004 non-null  float64
 4   Temperature             20004 non-null  float64
 5   Pressure                20004 non-null  float64
 6   Humidity                20004 non-null  float64
 7   WindDirection(Degrees)  20004 non-null  float64
 8   Speed                   20004 non-null  float64
 9   TimeSunRise             20004 non-null  str
 10  TimeSunSet              20004 non-null  str
 11  Date                    20004 non-null  str
 12  Date_num                20004 non-null  float64
dtypes: float64(8), int64(1), str(4)
memory usage: 2.6 MB

In [63]:
X_train = df_train[['Pressure','Humidity','Temperature','Speed','WindDirection(Degrees)','UNIXTime','Date_num']]

In [64]:
y_train = df_train['Radiation']

In [65]:
df_train['Radiation']

0          4.294954
1          4.439169
2        483.267515
3          5.950979
4         -8.324804
            ...
19999     10.210194
20000    323.399022
20001    419.397035
20002      4.582930
20003     15.813488
Name: Radiation, Length: 20004, dtype: float64

In [66]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
lr = LinearRegression()
rf = RandomForestRegressor(n_estimators=300,random_state=42)

In [67]:
rf.fit(X_train,y_train)

RandomForestRegressor(n_estimators=300, random_state=42)

In [68]:
lr.fit(X_train,y_train)

LinearRegression()

In [74]:
df_test_set['Radiation_rf'] = rf.predict(df_test_set)

In [77]:
df_test_set

,Pressure,Humidity,Temperature,Speed,WindDirection(Degrees),UNIXTime,Date_num,Radiation_rf
0,30.440000,75.960462,53.000000,6.750000,75.85,0.503098,0.505514,574.413614
1,30.422855,31.000000,46.000000,6.303768,173.63,1.559344,1.568414,7.592234
2,30.460000,99.000000,48.000000,1.120000,220.98,0.227863,0.218244,2.053541
3,30.422855,88.000000,43.000000,16.364613,208.21,1.750946,1.740776,1.536452
4,30.420000,96.000000,52.000000,4.500000,163.78,-1.690353,-1.677739,8.846698
...,...,...,...,...,...,...,...,...
3329,30.440000,65.000000,65.000000,7.870000,85.00,-0.182330,-0.183934,784.839644
3330,30.410000,90.000000,40.000000,11.250000,77.26,0.641753,0.649150,9.997513
3331,30.390000,64.000000,123.454239,12.370000,127.90,0.511078,0.505514,333.842661
3332,30.390000,101.000000,49.000000,4.500000,114.67,-1.143981,-1.131925,1.189155
3333,30.400000,69.000000,63.000000,1.120000,65.38,-0.989157,-0.988290,906.051413

In [80]:
df_test_set.to_csv('result.csv',index=False)